// Generated by jextract

package io.github.jbellis.jvector.vector.cnative;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_BOOLEAN);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "check_compatibility",
        constants$0.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "dot_product_f32",
        constants$0.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "euclidean_f32",
        constants$0.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "bulk_shuffle_dot_f32_512",
        constants$0.const$5
    );
}


